version: '2'
services:
  nginx:
    build: https://github.com/Ezerah/docker-nginx.git
    ports:
      - 80:80
      - 443:443
    links:
      - php
    volumes:
      - ./error.log:/var/log/nginx/error.log
      - ./html:/var/lib/wordpress/
      - ./socks:/var/run/dock/
  php:
    build: https://github.com/Ezerah/docker-php.git
    environment:
      - PHP_VERSION=5.0
    links:
      - percona
    volumes:
      - ./php-fpm.log:/var/log/php-fpm.log
      - ./html:/var/lib/wordpress/
      - ./socks:/var/run/dock/
  percona:
    build: https://github.com/Ezerah/docker-percona.git
    environment:
      - PERCONA_VERSION=5.7
